name: video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, and web.
repository: https://github.com/flutter/packages/tree/main/packages/video_player/video_player
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.9.2

environment:
  sdk: '>=3.0.0 <4.0.0'
#  flutter: ">=3.22.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: video_player_android
      ios:
        default_package: video_player_avfoundation
      macos:
        default_package: video_player_avfoundation
      web:
        default_package: video_player_web

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  video_player_android:
#    path: ../video_player_android # for local development
    git:
      url: https://github.com/invideoio/flutter-packages.git
      ref: feat/downgrade
      path: packages/video_player/video_player_android
  video_player_avfoundation:
#    path: ../video_player_avfoundation # for local development
    git:
      url: https://github.com/invideoio/flutter-packages.git
      ref: feat/downgrade
      path: packages/video_player/video_player_avfoundation
  video_player_platform_interface:
#    path: ../video_player_platform_interface # for local development
    git:
      url: https://github.com/invideoio/flutter-packages.git
      ref: feat/downgrade
      path: packages/video_player/video_player_platform_interface
  video_player_web:
#    path: ../video_player_web # for local development
    git:
      url: https://github.com/invideoio/flutter-packages.git
      ref: feat/downgrade
      path: packages/video_player/video_player_web

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - video
  - video-player
